---
title: 'Introduction to R, Class 3: Solutions'
output: github_document
---
  
<!--class3_solutions.md is generated from class3_solutions.Rmd. Please edit that file -->
  
  ```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
clinical <- read.csv("../data/clinical.csv")
```

#### Challenge-columns
```{r}
race_disease <- select(clinical, race, ethnicity, disease)
```

#### Challenge-rows
```{r}
race_BRCA <- filter(race_disease, disease == "BRCA")
```

#### Challenge-pipes
```{r}
clinical %>%
  filter(vital_status == "alive") %>%
  filter(cigarettes_per_day < 1) %>%
  select(gender, years_smoked, year_of_birth) %>%
  head() # output only the first few lines
```

#### Challenge-lung 
```{r}
clinical %>%
  filter(disease == "LUSC") %>%
  mutate(total_cig = years_smoked * cigarettes_per_day * 365) %>%
  head() # output only the first few lines
```

#### Challenge-smoke-complete
```{r}
smoke_complete <- clinical %>%
  filter(!is.na(age_at_diagnosis)) %>%
  filter(!is.na(cigarettes_per_day))
```

#### Challenge-save
```{r eval=FALSE}
write.csv(smoke_complete, "data/smoke_complete.csv", row.names = FALSE)
```
Google search for "save file R".

#### Challenge-birth-complete
```{r}
birth_complete <- clinical %>%
  filter(!is.na(year_of_birth)) %>%
  filter(!is.na(vital_status)) %>%
  filter(vital_status != "not reported")
```

#### Challenge-tumor
```{r}
# counting number of records for each tumor stage
tumor_counts <- clinical %>%
  count(tumor_stage)
# get names of tumors with many cases
frequent_tumors <- tumor_counts %>%
  filter(n > 200)
# extract data from cancers to keep
tumor_reduced <- clinical %>%
  filter(tumor_stage %in% frequent_tumors$tumor_stage)
```

## Extra exercises

#### Challenge-ethnicity
```{r}
clinical %>%
  filter(race != "white") %>% # only non-white individuals
  filter(ethnicity == "hispanic or latino") %>% # only hispanic/latino
  group_by(race) %>% # group by other races
  tally() # count total for each race
```

#### Challenge-years
```{r}
clinical <- clinical %>%
  mutate(age = year_of_death - year_of_birth)
```

#### Challenge-helpers
```{r}
# preferred way
clinical %>%
  select(contains("diagnosis")) %>%
  head() # output only the first few lines
# also works, but only because in this example both columns end in "diagnosis"
clinical %>%
  select(ends_with("diagnosis")) %>%
  head() # output only the first few lines
```

#### Challenge-combine
```{r}
clinical %>%
  filter(ethnicity == "hispanic or latino") %>%
  filter(year_of_death > 2000) %>%
  filter(!is.na(cigarettes_per_day)) %>%
  count()
```
